### ISSUE TITLE
Question : Melodic-devel availability

### ISSUE THREAD

**Issue by HasanFarag** [CNURobotics/flexible_manipulation#1]
Hello,

Is there a possibility to have the melodic-devel branch soon since we are migrating to melodic?

Thanks in advance

**Comment by dcconner** [comment]
We are using the system in Melodic right now as is.

**Comment by HasanFarag** [comment]
Thanks very much for your response. Can you please guide me in that?
I have Errors in melodic for compilation due to (it works fine in kinetic)
1. flexible_manipulation/flexible_manipulation_moveit_capabilities/src/extended_capabilities/move_group_extended_action_capability.cpp:43:0
2. flexible_manipulation/flexible_manipulation_moveit_capabilities/src/default_capabilities/kinematics_capability.cpp:188:108
3.flexible_manipulation/flexible_manipulation_moveit_capabilities/src/default_capabilities/get_cartesian_path_capability.cpp:203:95
4. /flexible_manipulation/flexible_manipulation_moveit_capabilities/src/helper/continuous_plan_execution.cpp:156:72

I see that they are tf and moveit transformation and msgs errors for melodic!

**Comment by dcconner** [comment]
My apologies.  I misread the email subject.  At this point, we don't have anyone using flexible_manipulation under Melodic.  Given current restrictions and deadlines, I don't see any of us getting to this in the next two to 3 months.  The changes required are not overly burdensome, and have been done for our flexible_navigation system.  Or you could also look at the corresponding  moveit changes.

**Comment by HasanFarag** [comment]
Thanks for your reply
